### ISSUE TITLE
`KeyError` about a missing `C_Label` column when submitting an accucor file with `H_Label` (or `D_Label`)

### ISSUE THREAD

**Issue by hepcat72** [Princeton-LSI-ResearchComputing/tracebase#1320]
### Problem

The submission start page encounters an uncaught exception when submitting an accucor file that has either a `D_Label` or `H_Label` column in the corrected sheet instead of a `C_Label` column.

### Steps to reproduce

1. Submit any of the accucor (excel) files from the `mneinast_exp048a_carnosine` study on the submission start page

### Current behavior

```
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 912, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socketserver.py", line 720, in __init__
    self.handle()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/DataRepo/views/upload/submission.py", line 669, in dispatch
    return super(BuildSubmissionView, self).dispatch(request, *args, **kwargs)
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/DataRepo/views/upload/submission.py", line 683, in post
    return self.form_valid(formset)
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/DataRepo/views/upload/submission.py", line 727, in form_valid
    self.set_files(
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/DataRepo/views/upload/submission.py", line 533, in set_files
    peak_annot_loader_class(
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/DataRepo/loaders/peak_annotations_loader.py", line 361, in __init__
    ConvertedTableLoader.__init__(self, *args, **kwargs)
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/DataRepo/loaders/base/converted_table_loader.py", line 1029, in __init__
    self.convert_df()
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/DataRepo/loaders/base/converted_table_loader.py", line 260, in convert_df
    raise self.aggregated_errors_object.buffer_error(ke)
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/DataRepo/utils/exceptions.py", line 2430, in buffer_error
    return self.buffer_exception(
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/DataRepo/utils/exceptions.py", line 2384, in buffer_exception
    buffered_tb_str = self.get_buffered_traceback_string()
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/DataRepo/utils/exceptions.py", line 2364, in get_buffered_traceback_string
    for step in traceback.format_stack()

The above caught exception had a partial traceback:

  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/DataRepo/loaders/base/converted_table_loader.py", line 243, in convert_df
    self.add_df_columns(outdf)
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/DataRepo/loaders/base/converted_table_loader.py", line 401, in add_df_columns
    df[sheet][new_column] = method(df[sheet])
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/DataRepo/loaders/peak_annotations_loader.py", line 2010, in <lambda>
    "isotopeLabel": lambda df: df.apply(
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/.venv/lib/python3.9/site-packages/pandas/core/frame.py", line 9568, in apply
    return op.apply().__finalize__(self, method="apply")
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/.venv/lib/python3.9/site-packages/pandas/core/apply.py", line 764, in apply
    return self.apply_standard()
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/.venv/lib/python3.9/site-packages/pandas/core/apply.py", line 891, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/.venv/lib/python3.9/site-packages/pandas/core/apply.py", line 907, in apply_series_generator
    results[i] = self.f(v)
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/DataRepo/loaders/peak_annotations_loader.py", line 2013, in <lambda>
    if row["C_Label"] > 0
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/.venv/lib/python3.9/site-packages/pandas/core/series.py", line 981, in __getitem__
    return self._get_value(key)
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/.venv/lib/python3.9/site-packages/pandas/core/series.py", line 1089, in _get_value
    loc = self.index.get_loc(label)
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/.venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
EXCEPTION1(ERROR): KeyError: 'C_Label'
Internal Server Error: /DataRepo/submission
Traceback (most recent call last):
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/.venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'C_Label'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/DataRepo/loaders/base/converted_table_loader.py", line 243, in convert_df
    self.add_df_columns(outdf)
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/DataRepo/loaders/base/converted_table_loader.py", line 401, in add_df_columns
    df[sheet][new_column] = method(df[sheet])
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/DataRepo/loaders/peak_annotations_loader.py", line 2010, in <lambda>
    "isotopeLabel": lambda df: df.apply(
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/.venv/lib/python3.9/site-packages/pandas/core/frame.py", line 9568, in apply
    return op.apply().__finalize__(self, method="apply")
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/.venv/lib/python3.9/site-packages/pandas/core/apply.py", line 764, in apply
    return self.apply_standard()
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/.venv/lib/python3.9/site-packages/pandas/core/apply.py", line 891, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/.venv/lib/python3.9/site-packages/pandas/core/apply.py", line 907, in apply_series_generator
    results[i] = self.f(v)
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/DataRepo/loaders/peak_annotations_loader.py", line 2013, in <lambda>
    if row["C_Label"] > 0
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/.venv/lib/python3.9/site-packages/pandas/core/series.py", line 981, in __getitem__
    return self._get_value(key)
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/.venv/lib/python3.9/site-packages/pandas/core/series.py", line 1089, in _get_value
    loc = self.index.get_loc(label)
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/.venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'C_Label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/DataRepo/views/upload/submission.py", line 669, in dispatch
    return super(BuildSubmissionView, self).dispatch(request, *args, **kwargs)
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/DataRepo/views/upload/submission.py", line 683, in post
    return self.form_valid(formset)
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/DataRepo/views/upload/submission.py", line 727, in form_valid
    self.set_files(
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/DataRepo/views/upload/submission.py", line 533, in set_files
    peak_annot_loader_class(
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/DataRepo/loaders/peak_annotations_loader.py", line 361, in __init__
    ConvertedTableLoader.__init__(self, *args, **kwargs)
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/DataRepo/loaders/base/converted_table_loader.py", line 1029, in __init__
    self.convert_df()
  File "/Users/rleach/PROJECT-local/TRACEBASE/tracebase/DataRepo/loaders/base/converted_table_loader.py", line 260, in convert_df
    raise self.aggregated_errors_object.buffer_error(ke)
DataRepo.utils.exceptions.AggregatedErrors: 1 exceptions occurred, including type(s): [KeyError].
AggregatedErrors Summary (1 errors / 0 warnings):
	EXCEPTION1(ERROR): KeyError: 'C_Label'
```

### Expected behavior

There should be no exception.  The conversion code should be able to handle other elements being in the column header.

### Suggested Change

Change the accucor conversion code to be able to handle the variable element in the `_Label` column.

### Comment

None

-----

### Assumptions

1. List of assumptions made WRT the code
2. E.g. We will assume input is correct (explaining why there is no validation)

### Limitations

1. A list of things this work will specifically not do
2. E.g. This feature will only handle the most frequent use case X

### Affected Components

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

#### GUI Change description

None provided

#### Code Change Description

None provided

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by mneinast** [comment]
it does seem like accucor changes the column name according to the element labeled.  I understand better that this is a needed fix.

**Comment by mneinast** [comment]
I could be wrong, but I think accucor might also generate an "N_Label" column if the labeled element is nitrogen.

**Comment by hepcat72** [comment]
> it does seem like accucor changes the column name according to the element labeled. I understand better that this is a needed fix.

OK, great, because I already have a second PR in the works with a fix.  I looked up the documentation for `Accucor` and added code to account for `D_Label` and `N_Label` columns.  I also added `H_Label`, since we have studies that made that change (because the underlying tracebase code doesn't support `D`.

I haven't put out the PR yet, but it passed all tests and I loaded everything into my sandbox with the changes:

<img width="1098" alt="image" src="https://github.com/user-attachments/assets/297bca90-cbdb-4039-9a34-97ee36bb0347">

```
Done.
Study records created: [1], existed: [0], deleted: [0], updated: [0], skipped [0], errored: [0], and warned: [0].
Compound records created: [6], existed: [60], deleted: [0], updated: [0], skipped [0], errored: [0], and warned: [0].
CompoundSynonym records created: [13], existed: [228], deleted: [0], updated: [0], skipped [0], errored: [0], and warned: [0].
Tracer records created: [3], existed: [0], deleted: [0], updated: [0], skipped [0], errored: [0], and warned: [0].
TracerLabel records created: [5], existed: [0], deleted: [0], updated: [0], skipped [0], errored: [0], and warned: [0].
InfusateTracer records created: [4], existed: [0], deleted: [0], updated: [0], skipped [0], errored: [0], and warned: [0].
Infusate records created: [4], existed: [0], deleted: [0], updated: [0], skipped [0], errored: [0], and warned: [0].
Protocol records created: [0], existed: [1], deleted: [0], updated: [0], skipped [0], errored: [0], and warned: [0].
Animal records created: [7], existed: [0], deleted: [0], updated: [0], skipped [0], errored: [0], and warned: [0].
AnimalLabel records created: [12], existed: [0], deleted: [0], updated: [0], skipped [0], errored: [0], and warned: [0].
Animal_studies records created: [7], existed: [0], deleted: [0], updated: [0], skipped [0], errored: [0], and warned: [0].
Tissue records created: [0], existed: [35], deleted: [0], updated: [0], skipped [0], errored: [0], and warned: [0].
FCirc records created: [52], existed: [0], deleted: [0], updated: [0], skipped [0], errored: [0], and warned: [0].
Sample records created: [30], existed: [0], deleted: [0], updated: [0], skipped [8], errored: [0], and warned: [0].
LCMethod records created: [0], existed: [5], deleted: [0], updated: [0], skipped [0], errored: [0], and warned: [0].
MSRunSequence records created: [1], existed: [0], deleted: [0], updated: [0], skipped [0], errored: [0], and warned: [0].
MSRunSample records created: [30], existed: [60], deleted: [0], updated: [0], skipped [43], errored: [0], and warned: [0].
PeakGroup records created: [1086], existed: [4508], deleted: [0], updated: [0], skipped [4964], errored: [0], and warned: [0].
ArchiveFile records created: [6], existed: [6], deleted: [0], updated: [0], skipped [0], errored: [0], and warned: [0].
PeakData records created: [5594], existed: [0], deleted: [0], updated: [0], skipped [4964], errored: [0], and warned: [0].
PeakDataLabel records created: [7552], existed: [60], deleted: [0], updated: [0], skipped [4400], errored: [0], and warned: [0].
PeakGroupLabel records created: [1658], existed: [5954], deleted: [0], updated: [0], skipped [4400], errored: [0], and warned: [0].
PeakGroup_compounds records created: [1146], existed: [4718], deleted: [0], updated: [0], skipped [5159], errored: [0], and warned: [0].
```

I'd had to add in the peak group conflicts sheet based on your prior selections when I'd updated the database.

I also saw that there are `mzXML` files in the carnosine study that are not in the ms data share.  There's a readme with a google drive link to them.  Could you add those to the data share?  I'm doing a download, but I'll need to scp them to the server.
