### ISSUE TITLE
Create `load_study` configuration for KR infusion dataset

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#252]
Create a YAML configuration file that can be used by [`load_study`](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/DataRepo/management/commands/load_study.py) Example: [`small_obob_study_params.yaml`](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/DataRepo/example_data/small_dataset/small_obob_study_params.yaml)

The configuration file and the required [KR infusion data files](https://drive.google.com/drive/folders/16WwulLp4ai_T4K4i6kZWjc1GBdW50MzW?usp=sharing) should be placed on the tracebase-dev server according to the [admin docs for loading studies](https://nplcadmindocs.princeton.edu/index.php/TraceBase#Loading_Studies).

**Comment by lparsons** [comment]
@hepcat72 Regarding `DataRepo.utils.RequiredValueError: Values in column Researcher Name are required, but some found missing`, this is a known "issue" (#261). The fix is to either fill in the column with values or delete the column entirely. Record you edits in a `README.md` file to be reported back to the researchers and stored with the study files.

**Comment by hepcat72** [comment]
I'm not sure #261 is the issue, as all the rows with data have a value for researcher name... My hunch is that it's treating completely empty rows as data rows...

**Comment by hepcat72** [comment]
Yeah.  Confirmed.  It's reading 969155 rows of the file and hits the error on the first empty row... I don't know how to tell it to only read rows with data.  Going to google some more.  First google result said to supply `keep_default_na=False `, but that's already done.

**Comment by hepcat72** [comment]
Well, I was trying to figure this out while waiting to see if Sven had time fore the galaxy stuff (or what the strategy there would be). Going to switch over to galaxy since it looks like that should move forward today...

Currently, this is stuck trying to read empty lines and I was trying code edits to try and drop the empty rows... Maybe I should just copy the data into an empty excel spreadsheet...

**Comment by jcmatese** [comment]
I did a quick web search and nothing really popped up. Seems like a pre-screening would have to be done, to find the shape (i.e. first missing row), then use that number for either `read_excel`'s or `read_csv`'s argument of `nrows` ...

**Comment by hepcat72** [comment]
Yeah, I was thinking similarly...  Was hoping there would be a simpler solution. Se la vie (sp?).

**Comment by jcmatese** [comment]
Perhaps [solution 2 here would be simpler](https://stackoverflow.com/questions/41045510/pandas-read-csv-ignore-rows-after-a-blank-line) i.e. `df.dropna(axis=0, how='any', inplace=True)` but it would seems that not reading in 900k empty rows in the first place would be preferable?

**Comment by lparsons** [comment]
If I download [TraceBase Reference_MN_exp027e K and R infusion](https://docs.google.com/spreadsheets/d/14jt__E25g2KKPL22ninDR1ptek1aCHLTwsv8hCjAv34/edit?usp=sharing) as an Excel file ([TraceBase Reference_MN_exp027e K and R infusion.xlsx](https://github.com/Princeton-LSI-ResearchComputing/tracebase/files/7663684/TraceBase.Reference_MN_exp027e.K.and.R.infusion.xlsx)), I am able to load it without issue using `pandas==1.3.4` and `openpyxl==3.0.7`:
```python
import pandas as pd
df = pd.read_excel("/home/lparsons/Downloads/TraceBase Reference_MN_exp027e K and R infusion.xlsx")
```
I also tried reading the two AccuCor files in the directory:
```python
df = pd.read_excel("/home/lparsons/Downloads/exp027e_pos_highmz_corrected.xlsx")
df = pd.read_excel("/home/lparsons/Downloads/exp027e_pos_lowmz_corrected.xlsx")
```

![image](https://user-images.githubusercontent.com/645128/144927036-8cb6274b-b6ad-42a2-a8d5-133ed7d0406f.png)

**Comment by hepcat72** [comment]
I *did* read that newer versions of pandas may fix the issue with reading empty rows.

**Comment by lparsons** [comment]
> I _did_ read that newer versions of pandas may fix the issue with reading empty rows.

I believe the versions I used were the ones specified in the current `main` branch. If it still gives you trouble, perhaps post the problematic file here.

**Comment by hepcat72** [comment]
Is that merged now?  And when will it go to dev?

**Comment by lparsons** [comment]
Yes, it's merged. https://github.com/Princeton-LSI-ResearchComputing/tracebase/commit/579edf0aaa95eb705b77877a3be0e0cb7d8263a0#diff-bf1b1fe7bf334bb5f5589d4366b2c17ea1f5a3a45668188aef31c324f2a34f20R7

We can push it to dev whenever, I was mainly waiting to get the various PRs merged.

**Comment by hepcat72** [comment]
The KR infusion data folder is ready to go, though it can't be loaded onto dev until the changes from PR #290 is pushed out to dev.

**Comment by lparsons** [comment]
@hepcat72 The study failed to load on tracebase-dev (using the latest `main`) with the following error:
```
Importing animals and samples...
Checking researchers...
Created new record: Study:MN_exp027e_acute KR infusion
Adding animal to the study...
Created new record: Animal:MN_exp027e_M1
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/tracebase/lib64/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/tracebase/lib64/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/tracebase/lib64/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/tracebase/lib64/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/var/www/tracebase/DataRepo/management/commands/load_study.py", line 86, in handle
    call_command(
  File "/usr/local/tracebase/lib64/python3.8/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/tracebase/lib64/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/var/www/tracebase/DataRepo/management/commands/load_animals_and_samples.py", line 115, in handle
    loader.load_sample_table(
  File "/var/www/tracebase/DataRepo/utils.py", line 216, in load_sample_table
    age = self.getRowVal(row, self.headers.ANIMAL_AGE, hdr_required=False)
  File "/var/www/tracebase/DataRepo/utils.py", line 395, in getRowVal
    raise RequiredValueError(
DataRepo.utils.RequiredValueError: Values in column Age are required, but some found missing
```
I'm currently investigating.

**Comment by hepcat72** [comment]
That was the error I was getting when using the old pandas/openpyxl.  My bet is it's probably processing empty rows again somehow.  Are you using the files I slacked to you?  I didn't copy my folder anywhere with the latest changes (other than in the slack message to you the other day).  I was assuming that I would copy over and load the data when I heard back from you.  Which version of the data did you use?

**Comment by lparsons** [comment]
No, I'm using the files that are in `tracebase-dev:/var/www/tracebase/datasets/MN_exp027e_KR_infusion`.

**Comment by hepcat72** [comment]
OK. I will copy over the latest. Didn't know you would attempt to load.  Sorry.

**Comment by lparsons** [comment]
All set, data is loaded now. 👍🏻
