### ISSUE TITLE
PeakData results cause a `NoReverseMatch` Exception when an animal has no tracer specified

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#312]
### Problem

Viewing the PeakData for studies where some animals have no tracer specified causes a `NoReveserMatch` Excpetion.

The animal `MN_exp027e_M1` was loaded incorrectly without a tracer. It appears that the tracer should be `arginine`. It's possible (likely) the other animals in the study were also loaded incorrectly. However, we have determined that TraceBase *should* support Animals with no tracer (see #325).

### Steps to reproduce

1. Load the MN exp027e KR infusion study - see https://github.com/PrincetonUniversity/tracebase-rabinowitz-data/pull/4

*Note:* This should be more easily reproduced when #325 is completed.

This was discovered attempting to view PeakData for the (incorrectly loaded) "MN_exp027e_acute KR infusion" study on tracebase-dev, which caused a `NoReverseMatch` exception.

1. View study list - http://tracebase-dev.princeton.edu/DataRepo/studies/
2. View Study "MN_exp027e_acute KR infusion" - http://tracebase-dev.princeton.edu/DataRepo/studies/3/
3. Click on link to view PeakData - http://tracebase-dev.princeton.edu/DataRepo/search_basic/Study/id/exact/3/peakdata/

### Current behavior

```
Environment:


Request Method: GET
Request URL: http://tracebase-dev.princeton.edu/DataRepo/search_basic/Study/id/exact/3/peakdata/

Django Version: 3.2.5
Python Version: 3.8.8
Installed Applications:
['DataRepo.apps.DatarepoConfig',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']


Template error:
In template /var/www/tracebase/DataRepo/templates/DataRepo/search/results/peakdata.html, error at line 236
   Reverse for 'compound_detail' with arguments '('',)' not found. 1 pattern(s) tried: ['DataRepo/compounds/(?P<pk>[0-9]+)/$']
   226 : 
   227 :                             <!-- Treatment -->
   228 :                             <td>
   229 :                                 {{ pd.peak_group.msrun.treatment.name }}
   230 :                             </td>
   231 : 
   232 :                             <!-- Tracer Compound -->
   233 :                             <td>
   234 :                                 <!-- Put displayed link text first for sorting -->
   235 :                                 <div style="display:none;">{{ pd.peak_group.msrun.sample.animal.tracer_compound.name }}</div>
   236 :                                 <a href=" {% url 'compound_detail' pd.peak_group.msrun.sample.animal.tracer_compound.id %} ">
   237 :                                     {{ pd.peak_group.msrun.sample.animal.tracer_compound.name }}
   238 :                                 </a>
   239 :                             </td>
   240 : 
   241 :                             <!-- Tracer Infusion Rate (ul/min/g) -->
   242 :                             <td class="text-end">
   243 :                                 {{ pd.peak_group.msrun.sample.animal.tracer_infusion_rate }}
   244 :                             </td>
   245 : 
   246 :                             <!-- Tracer Infusion Concentration (mM) -->


Traceback (most recent call last):
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/tracebase/DataRepo/views.py", line 266, in search_basic
    return render(
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/loader_tags.py", line 195, in render
    return template.render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/loader_tags.py", line 53, in render
    result = self.nodelist.render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/loader_tags.py", line 195, in render
    return template.render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/loader_tags.py", line 53, in render
    result = self.nodelist.render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/template/defaulttags.py", line 446, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/usr/local/tracebase/lib/python3.8/site-packages/django/urls/resolvers.py", line 694, in _reverse_with_prefix
    raise NoReverseMatch(msg)

Exception Type: NoReverseMatch at /DataRepo/search_basic/Study/id/exact/3/peakdata/
Exception Value: Reverse for 'compound_detail' with arguments '('',)' not found. 1 pattern(s) tried: ['DataRepo/compounds/(?P<pk>[0-9]+)/$']
```

### Expected behavior

A list of PeakData records belonging to that Study

### Suggested Change

Something with the compound id seems incorrect for at least one row.

### Comment

Note, the corresponding tsv format should also be affected by this...

-----

### Assumptions

none

### Requirements

- Allow no tracer foreign key to exist
- Show fields that require a tracer as "None"

### Limitations

none

### Affected/Changed Components

- peakdata.html
- peakdata.tsv

I will also do:

- peakgroups.html
- peakgroups.tsv

The fcirc templates should be unaffected because they only show data that is associated with tracers.

#### GUI Change description

No exception thrown when trying to search (and download) and getting animals without tracers.

#### Code Change Description *(Pseudocode optional)*

Create a conditional that checks for a tracer foreign key before rendering any compound data for the tracer.

#### Tests

Render a record with no tracer.

**Comment by hepcat72** [comment]
At first glance, it appears that perhaps there's an animal without a tracer compound foreign key, because it's complaining about an empty string (`''`) being supplied as the ID in the URL tag.

**Comment by hepcat72** [comment]
Yep.  Animal `MN_exp027e_M1` has no tracer.  Before I allow for this possibility, I just want to check if we're sure we want to allow animal records without tracers? @fkang-pu @lparsons @jcmatese

**Comment by jcmatese** [comment]
Uncertain (will have to confirm with lab)...  On the one hand, you can definitely measure metabolites with MS without the needs for radio-labeling.  On the other hand, much of the calculations and views are probably geared towards it (tracer-based comparisons)...

**Comment by lparsons** [comment]
It's not clear to me that we want to allow an animal without a tracer. Either we should allow for this (and handle these issue in the templates) or we should decide to not allow it and fix the issue in the loading code that created this in the first place. My hunch is that not allowing would be simpler and thus preferred. I will check with @mneinast and if this animal should have a tracer and update this issue.

**Comment by lparsons** [comment]
So, I don't think we need input from @mneinast after all. This appears to be a bug in the loading code since the [animal table clearly indicates that the tracer should be arginine](https://docs.google.com/spreadsheets/d/10ZuTmfxdrBJZQL7-gfyIbJs1A-CRyirE/edit#gid=803792089).

**Comment by lparsons** [comment]
> I could add a catch for this somewhere to supply a cogent error message...? Otherwise, I removed myself to focus on other issues.

I don't think we need to worry about it, esp. if we fix the underlying issue that allowed this to be created in the first place.

**Comment by jcmatese** [comment]
Could there have been a header mismatch in the loading specification?

**Comment by lparsons** [comment]
Asked lab members to weigh in on the potential need for recording samples from animals with no tracer: https://tracebase.slack.com/archives/C01M97YLQE5/p1641400830123300
