### ISSUE TITLE
Unexpected error when running through the CONTRIBUTING steps

### ISSUE THREAD

**Issue by jcmatese** [Princeton-LSI-ResearchComputing/tracebase#372]
This is probably just some misconfiguration of my developmental sandbox after trying to migrate to the new validation scheme.

Everything seem ok through the steps

```
   python manage.py migrate
   python manage.py createcachetable
   python manage.py migrate --database validation
   python manage.py createcachetable --database validation
```

but when continuing

```
$ python manage.py load_compounds --compounds DataRepo/example_data/consolidated_tracebase_compound_list.tsv
Added cached_function decorator to function Animal.final_serum_sample
Added cached_function decorator to function Animal.final_serum_sample_id
Added cached_function decorator to function Animal.all_serum_samples_tracer_peak_groups
Added cached_function decorator to function Animal.final_serum_sample_tracer_peak_group
Added cached_function decorator to function Animal.intact_tracer_peak_data
Added cached_function decorator to function Animal.final_serum_tracer_rate_disappearance_intact_per_gram
Added cached_function decorator to function Animal.final_serum_tracer_rate_appearance_intact_per_gram
Added cached_function decorator to function Animal.final_serum_tracer_rate_disappearance_intact_per_animal
Added cached_function decorator to function Animal.final_serum_tracer_rate_appearance_intact_per_animal
Added cached_function decorator to function Animal.final_serum_tracer_rate_disappearance_average_per_gram
Added cached_function decorator to function Animal.final_serum_tracer_rate_appearance_average_per_gram
Added cached_function decorator to function Animal.final_serum_tracer_rate_disappearance_average_per_animal
Added cached_function decorator to function Animal.final_serum_tracer_rate_appearance_average_per_animal
Added cached_function decorator to function Animal.final_serum_tracer_rate_appearance_average_atom_turnover
Added cached_function decorator to function Sample.is_serum_sample
Added cached_function decorator to function PeakGroup.enrichment_fraction
Added cached_function decorator to function PeakGroup.enrichment_abundance
Added cached_function decorator to function PeakGroup.normalized_labeling
Added cached_function decorator to function PeakGroup.is_tracer_compound_group
Added cached_function decorator to function PeakGroup.from_serum_sample
Added cached_function decorator to function PeakGroup.can_compute_tracer_rates
Added cached_function decorator to function PeakGroup.can_compute_intact_tracer_rates
Added cached_function decorator to function PeakGroup.can_compute_average_tracer_rates
Added cached_function decorator to function PeakGroup.rate_disappearance_intact_per_gram
Added cached_function decorator to function PeakGroup.rate_appearance_intact_per_gram
Added cached_function decorator to function PeakGroup.rate_disappearance_intact_per_animal
Added cached_function decorator to function PeakGroup.rate_appearance_intact_per_animal
Added cached_function decorator to function PeakGroup.rate_disappearance_average_per_gram
Added cached_function decorator to function PeakGroup.rate_appearance_average_per_gram
Added cached_function decorator to function PeakGroup.rate_disappearance_average_per_animal
Added cached_function decorator to function PeakGroup.rate_appearance_average_per_animal
Added cached_function decorator to function PeakGroup.rate_appearance_average_atom_turnover
Loading compound data
Work to be done: 0 new compounds will be inserted and all names/synonyms from the file will either be found or inserted.
Traceback (most recent call last):
  File "/Users/jcmatese/dev/tracebase/manage.py", line 22, in <module>
    main()
  File "/Users/jcmatese/dev/tracebase/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/jcmatese/dev/tracebase/.venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/Users/jcmatese/dev/tracebase/.venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/jcmatese/dev/tracebase/.venv/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/jcmatese/dev/tracebase/.venv/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/Users/jcmatese/dev/tracebase/DataRepo/management/commands/load_compounds.py", line 111, in handle
    loader.load_synonyms()
  File "/Users/jcmatese/dev/tracebase/DataRepo/utils.py", line 1361, in load_synonyms
    self.load_synonyms_per_db(settings.VALIDATION_DB)
  File "/Users/jcmatese/dev/tracebase/DataRepo/utils.py", line 1378, in load_synonyms_per_db
    hmdb_compound = Compound.objects.using(db).get(hmdb_id=hmdb_id)
  File "/Users/jcmatese/dev/tracebase/.venv/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
DataRepo.models.DoesNotExist: Compound matching query does not exist.
```

Uncertain what the issue actually is.  Probably something small, and may be localized to my environment.  I just hadn't seen it before.

**Comment by jcmatese** [comment]
And the next step lists a file that might not exist, in my sandbox anyway.  Turned off DEBUG because of "Added cached_function decorator" distraction

```
(.venv) jcmatese@gen-matesembp:~/dev/tracebase(server_pagination) $ python manage.py load_study DataRepo/example_data/tissues/tissues.yaml
usage: manage.py load_study [-h] [--version] [-v {0,1,2,3}] [--settings SETTINGS] [--pythonpath PYTHONPATH] [--traceback] [--no-color] [--force-color] [--skip-checks] study_params
manage.py load_study: error: argument study_params: can't open 'DataRepo/example_data/tissues/tissues.yaml': [Errno 2] No such file or directory: 'DataRepo/example_data/tissues/tissues.yaml'

**Comment by hepcat72** [comment]
I know what's happening here.  `validate_data` is only checking 1 database (the regular tracebase database) and loading the resulting compounds into both the tracebase and the validation database.  In other words, it assumes that the databases are starting out the same.  In your case:

```
Work to be done: 0 new compounds will be inserted and all names/synonyms from the file will either be found or inserted.
```

You already had the compounds loaded.  You have 2 options:

1. Clear out your tracebase database and start fresh
2. Call load_compounds again and supply `--database validation`

If we feel that this issue should be addressed in the code, I could add a check in the `validate_data` method to account for the possibility that the 2 databases are out of synch...

**Comment by jcmatese** [comment]
Thanks, that is the resolution. [supply `--database validation`]

**Comment by hepcat72** [comment]
Unless anyone wants to propose specific changes for this issue, I propose we close it as a `wontfix`.

**Comment by lparsons** [comment]
@jcmatese can we close this?

**Comment by jcmatese** [comment]
I suppose so.  I don't _think_ it will trouble me again, but I don't know what circumstances might cause it to pop up.  It is definitely not high on my list of concerns
