### ISSUE TITLE
Archive File Detail page for "raw" files throws and exception

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#910]
### Problem

The archive file detail page for "raw" format files throws and exception since the file is not actually stored but the template attempts to get the url regardless.

### Steps to reproduce

1. Navigate to the detail view of an archive file for a "raw" file

### Current behavior

```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/DataRepo/archive_file/85/

Django Version: 4.2.10
Python Version: 3.9.18
Installed Applications:
['DataRepo.apps.DatarepoConfig',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'DataRepo.tests.apps.test_apps.LoaderTestConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']


Template error:
In template /home/lparsons/Documents/projects/tracebase/DataRepo/templates/DataRepo/archive_file_detail.html, error at line 32
   The 'file_location' attribute has no file associated with it.
   22 :         <tr>
   23 :             <td>Data Type</td>
   24 :             <td>{{ archivefile.data_type }}</td>
   25 :         </tr>
   26 :         <tr>
   27 :             <td>Data Format</td>
   28 :             <td>{{ archivefile.data_format }}</td>
   29 :         </tr>
   30 :         <tr>
   31 :             <td>File Location</td>
   32 :             <td><a href=" {{ archivefile.file_location.url }} ">{{ archivefile.filename }}<a/></td>
   33 :         </tr>
   34 :     </table>
   35 : </div>
   36 : 
   37 : <h5>{% if archivefile.data_type.code == "ms_peak_annotation" %}
   38 :     <a href="{% url 'search_basic' 'PeakAnnotationFile' 'id' 'iexact' archivefile.pk 'peakgroups' %}">Peak Group Data</a></h5>
   39 : {% elif archivefile.data_format.code == "ms_raw" %}
   40 :     <a href="{% url 'search_basic' 'RAWFile' 'id' 'iexact' archivefile.pk 'peakgroups' %}">Peak Group Data</a></h5>
   41 : {% elif archivefile.data_format.code == "mzxml" %}
   42 :     <a href="{% url 'search_basic' 'MZFile' 'id' 'iexact' archivefile.pk 'peakgroups' %}">Peak Group Data</a></h5>


Traceback (most recent call last):
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]

During handling of the above exception ('FieldFile' object is not subscriptable), another exception occurred:
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/template/base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/template/base.py", line 715, in resolve
    obj = self.var.resolve(context)
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/template/base.py", line 890, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/db/models/fields/files.py", line 66, in url
    self._require_file()
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/db/models/fields/files.py", line 41, in _require_file
    raise ValueError(

Exception Type: ValueError at /DataRepo/archive_file/85/
Exception Value: The 'file_location' attribute has no file associated with it.
```

### Expected behavior

View page with no download link, instead a note that the file is not stored in TraceBase at this time.

### Suggested Change

None provided

### Comment

None

-----

### Assumptions

1. List of assumptions made WRT the code
2. E.g. We will assume input is correct (explaining why there is no validation)

### Limitations

1. A list of things this work will specifically not do
2. E.g. This feature will only handle the most frequent use case X

### Affected Components

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

#### GUI Change description

None provided

#### Code Change Description

None provided

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by hepcat72** [comment]
This was fixed in #953 (but the merge was handled further down the PR chain).
