### ISSUE TITLE
Attempted rollback of ArchiveFile operations results in Exception

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/tracebase#990]
### Problem

Any exception that causes an attempted rollback of an ArchiveFile operation results in a Exception attempting to delete a file for an existing record.

### Steps to reproduce

Any exception encountered when attempting to load an `mzXML` file will result in this exception, however one way to reproduce it relatively simply is to attempt to load an `mzXML` file that does not match any existing sample.

1. Login to `tracebase-dev`
    ```bash
    ssh tracebase-dev.princeton.edu
    ```
2. `sudo` as the `tracebase` user
    ```bash
    sudo -iu tracebase
    ```
3. Source the tracebase conda env
    ```bash
    source /usr/local/tracebase/bin/activate
    ```
4. Attempt to load an `mzXML` file that does not correspond to an existing sample
    ```bash
    cd "/tracebase-staging/loaded/exp027f_long_kli_timecourse"
    python /var/www/tracebase/manage.py load_msruns \
      --mzxml-files './220909_exp027f4_free plasma and tissues/scan2/skipped_samples/exp027f4_free_M01_01_plasma.mzXML' \
      --instrument "Exploris480" \
      --date "2022-09-09" \
      --lc-protocol-name "polar-HILIC-25-min" \
      --operator "Michael Neinast"
    ```

### Current behavior

```pytb
  File "/var/www/tracebase/manage.py", line 22, in <module>
    main()
  File "/var/www/tracebase/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/var/www/tracebase/DataRepo/management/commands/load_table.py", line 382, in handle_wrapper
    retval = fn(self, *args, **options)
  File "/var/www/tracebase/DataRepo/management/commands/load_msruns.py", line 136, in handle
    self.load_data()
  File "/var/www/tracebase/DataRepo/management/commands/load_table.py", line 423, in load_data
    return self.loader.load_data(*args, **kwargs)
  File "/var/www/tracebase/DataRepo/loaders/table_loader.py", line 1951, in load_wrapper
    retval = fn(*args, **kwargs)
  File "/var/www/tracebase/DataRepo/loaders/msruns_loader.py", line 385, in load_data
    sample = self.get_sample_by_name(sample_name, from_mzxml=True)
  File "/var/www/tracebase/DataRepo/loaders/msruns_loader.py", line 786, in get_sample_by_name
    self.aggregated_errors_object.buffer_error(
  File "/var/www/tracebase/DataRepo/utils/exceptions.py", line 1415, in buffer_error
    return self.buffer_exception(
  File "/var/www/tracebase/DataRepo/utils/exceptions.py", line 1369, in buffer_exception
    buffered_tb_str = self.get_buffered_traceback_string()
  File "/var/www/tracebase/DataRepo/utils/exceptions.py", line 1349, in get_buffered_traceback_string
    for step in traceback.format_stack()

The above caught exception had a partial traceback:

  File "/var/www/tracebase/DataRepo/loaders/msruns_loader.py", line 778, in get_sample_by_name
    rec = Sample.objects.get(name=sample_name)
  File "/usr/local/tracebase/lib/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/tracebase/lib/python3.9/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
EXCEPTION2(ERROR): RecordDoesNotExist: Sample record matching the mzXML file's basename [exp027f4_free_M01_01_plasma] does not exist.  Please identify the associated sample and add a row with it, the matching mzXML file name(s), and the Sequence Name to the Peak Annotation Details sheet/file.
  File "/var/www/tracebase/manage.py", line 22, in <module>
    main()
  File "/var/www/tracebase/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/var/www/tracebase/DataRepo/management/commands/load_table.py", line 382, in handle_wrapper
    retval = fn(self, *args, **options)
  File "/var/www/tracebase/DataRepo/management/commands/load_msruns.py", line 136, in handle
    self.load_data()
  File "/var/www/tracebase/DataRepo/management/commands/load_table.py", line 423, in load_data
    return self.loader.load_data(*args, **kwargs)
  File "/var/www/tracebase/DataRepo/loaders/table_loader.py", line 1951, in load_wrapper
    retval = fn(*args, **kwargs)
  File "/var/www/tracebase/DataRepo/loaders/msruns_loader.py", line 400, in load_data
    self.clean_up_created_mzxmls_in_archive()
  File "/var/www/tracebase/DataRepo/loaders/msruns_loader.py", line 1507, in clean_up_created_mzxmls_in_archive
    self.aggregated_errors_object.buffer_error(
  File "/var/www/tracebase/DataRepo/utils/exceptions.py", line 1415, in buffer_error
    return self.buffer_exception(
  File "/var/www/tracebase/DataRepo/utils/exceptions.py", line 1369, in buffer_exception
    buffered_tb_str = self.get_buffered_traceback_string()
  File "/var/www/tracebase/DataRepo/utils/exceptions.py", line 1349, in get_buffered_traceback_string
    for step in traceback.format_stack()
EXCEPTION3(ERROR): ProgrammingError: Cannot delete a file [/tracebasedev-archive/archive/archive_files/2024-06/ms_data/exp027f4_free_M01_01_plasma_wP9ious.mzXML] from the os that is associated with existing ArchiveFile database record: {'id': 652, 'filename': 'exp027f4_free_M01_01_plasma.mzXML', 'checksum': 'f9d2074dff00cf659a0888617bc92163725a45e4', 'file_location': <FieldFile: archive_files/2024-06/ms_data/exp027f4_free_M01_01_plasma_wP9ious.mzXML>, 'data_type': 2, 'data_format': 4}.
mzXML file rollback disk archive clean up stats: 0 deleted, 0 failed to be deleted, and 0 expected files did not exist.
```

### Expected behavior

The `RecordDoesNotExist` exception should be reported and the copy of `mzXML` file should no longer be in the archive directory.

### Comment

-----

### Assumptions

1. List of assumptions made WRT the code
2. E.g. We will assume input is correct (explaining why there is no validation)

### Limitations

1. A list of things this work will specifically not do
2. E.g. This feature will only handle the most frequent use case X

### Affected Components

- change: File path or DB table ...
- add: Environment variable or server setting
- delete: External executable or cron job

### Requirements

- [ ] 1. List of numbered conditions to be met for the feature
- [ ] 2. E.g. Every column/row must display a value, i.e. cannot be empty
- [ ] 3. Numbers for reference & checkboxes for progress tracking

#### GUI Change description

None provided

#### Code Change Description

None provided

#### Tests

- [ ] 1. A description of at least one test for each requirement above.
- [ ] 2. E.g. Test for req 2 that there's an exception when display value is ''
- [ ] 3. Numbers for reference & checkboxes for progress tracking

**Comment by hepcat72** [comment]
Just a few notes...

Not important for this specific issue, but the sample record indeed does not exist:

```
In [1]: from DataRepo.models import Sample

In [2]: Sample.objects.get(name="exp027f4_free_M01_01_plasma")
---------------------------------------------------------------------------
DoesNotExist                              Traceback (most recent call last)
<ipython-input-2-c7f022d0b3cd> in <module>
----> 1 Sample.objects.get(name="exp027f4_free_M01_01_plasma")

/usr/local/tracebase/lib/python3.9/site-packages/django/db/models/manager.py in manager_method(self, *args, **kwargs)
     85             @wraps(method)
     86             def manager_method(self, *args, **kwargs):
---> 87                 return getattr(self.get_queryset(), name)(*args, **kwargs)
     88 
     89             return manager_method

/usr/local/tracebase/lib/python3.9/site-packages/django/db/models/query.py in get(self, *args, **kwargs)
    635             return clone._result_cache[0]
    636         if not num:
--> 637             raise self.model.DoesNotExist(
    638                 "%s matching query does not exist." % self.model._meta.object_name
    639             )

DoesNotExist: Sample matching query does not exist.
```

I think that probably, the `ArchiveFile` record should be allowed to be created.  No expected sample was provided with the mzXML file.  It's the attempted automated lookup based on the filename that fails.  It should probably be a warning, not an error that causes a rollback.  We want to be able to load mzXML files at any time.

Another note is that this sample, according to the Samples sheet is a sample that is to be excluded.  Thus, the `Peak Annotation Details` sheet must be supplied and `skip` must be entered in the `skip` column to skip it.  This could suggest that there could exist a way to supply a `--skip` option to skip MSRunSamples to complement the automatic handling of mapping mzxml file names to samples in the database.  (And again, this is unrelated to this specific issue.)

The first exception is a `NoLoadData` **warning**.  This exception is suppressed from the summary, because it is handled retro-actively.

Although it should be a warning, the `MissingRecords` exception should be a `MissingSamples` exception.

Lastly, here is an updated trace (during buffering) for all the exceptions that come out:

```
  File "/var/www/tracebase/manage.py", line 22, in <module>
    main()
  File "/var/www/tracebase/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/var/www/tracebase/DataRepo/management/commands/load_table.py", line 408, in handle_wrapper
    retval = fn(self, *args, **options)
  File "/var/www/tracebase/DataRepo/management/commands/load_msruns.py", line 150, in handle
    self.load_data()
  File "/var/www/tracebase/DataRepo/management/commands/load_table.py", line 448, in load_data
    return self.loader.load_data(*args, **kwargs)
  File "/var/www/tracebase/DataRepo/loaders/base/table_loader.py", line 2110, in load_wrapper
    self.check_dataframe_headers()
  File "/var/www/tracebase/DataRepo/loaders/base/table_loader.py", line 1332, in check_dataframe_headers
    self.aggregated_errors_object.buffer_warning(
  File "/var/www/tracebase/DataRepo/utils/exceptions.py", line 2366, in buffer_warning
    return self.buffer_exception(
  File "/var/www/tracebase/DataRepo/utils/exceptions.py", line 2315, in buffer_exception
    buffered_tb_str = self.get_buffered_traceback_string()
  File "/var/www/tracebase/DataRepo/utils/exceptions.py", line 2295, in get_buffered_traceback_string
    for step in traceback.format_stack()
EXCEPTION1(WARNING): NoLoadData: No dataframe [df] provided.  Nothing to load.
  File "/var/www/tracebase/manage.py", line 22, in <module>
    main()
  File "/var/www/tracebase/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/var/www/tracebase/DataRepo/management/commands/load_table.py", line 408, in handle_wrapper
    retval = fn(self, *args, **options)
  File "/var/www/tracebase/DataRepo/management/commands/load_msruns.py", line 150, in handle
    self.load_data()
  File "/var/www/tracebase/DataRepo/management/commands/load_table.py", line 448, in load_data
    return self.loader.load_data(*args, **kwargs)
  File "/var/www/tracebase/DataRepo/loaders/base/table_loader.py", line 2114, in load_wrapper
    retval = fn(*args, **kwargs)
  File "/var/www/tracebase/DataRepo/models/maintained_model.py", line 1241, in wrapper
    fn(*args, **kwargs)
  File "/var/www/tracebase/DataRepo/loaders/msruns_loader.py", line 492, in load_data
    sample = self.get_sample_by_name(sample_name, from_mzxml=True)
  File "/var/www/tracebase/DataRepo/loaders/msruns_loader.py", line 1049, in get_sample_by_name
    self.aggregated_errors_object.buffer_error(
  File "/var/www/tracebase/DataRepo/utils/exceptions.py", line 2361, in buffer_error
    return self.buffer_exception(
  File "/var/www/tracebase/DataRepo/utils/exceptions.py", line 2315, in buffer_exception
    buffered_tb_str = self.get_buffered_traceback_string()
  File "/var/www/tracebase/DataRepo/utils/exceptions.py", line 2295, in get_buffered_traceback_string
    for step in traceback.format_stack()

The above caught exception had a partial traceback:

  File "/var/www/tracebase/DataRepo/loaders/msruns_loader.py", line 1041, in get_sample_by_name
    rec = Sample.objects.get(name=sample_name)
  File "/usr/local/tracebase/lib/python3.9/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/tracebase/lib/python3.9/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
EXCEPTION2(ERROR): RecordDoesNotExist: Sample record matching the mzXML file's basename [exp027f4_free_M01_01_plasma] does not exist.  Please identify the associated sample and add a row with it, the matching mzXML file name(s), and the Sequence Name to the Peak Annotation Details sheet/file.
  File "/var/www/tracebase/manage.py", line 22, in <module>
    main()
  File "/var/www/tracebase/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/var/www/tracebase/DataRepo/management/commands/load_table.py", line 408, in handle_wrapper
    retval = fn(self, *args, **options)
  File "/var/www/tracebase/DataRepo/management/commands/load_msruns.py", line 150, in handle
    self.load_data()
  File "/var/www/tracebase/DataRepo/management/commands/load_table.py", line 448, in load_data
    return self.loader.load_data(*args, **kwargs)
  File "/var/www/tracebase/DataRepo/loaders/base/table_loader.py", line 2114, in load_wrapper
    retval = fn(*args, **kwargs)
  File "/var/www/tracebase/DataRepo/models/maintained_model.py", line 1241, in wrapper
    fn(*args, **kwargs)
  File "/var/www/tracebase/DataRepo/loaders/msruns_loader.py", line 507, in load_data
    self.clean_up_created_mzxmls_in_archive()
  File "/var/www/tracebase/DataRepo/loaders/msruns_loader.py", line 1794, in clean_up_created_mzxmls_in_archive
    self.aggregated_errors_object.buffer_error(
  File "/var/www/tracebase/DataRepo/utils/exceptions.py", line 2361, in buffer_error
    return self.buffer_exception(
  File "/var/www/tracebase/DataRepo/utils/exceptions.py", line 2315, in buffer_exception
    buffered_tb_str = self.get_buffered_traceback_string()
  File "/var/www/tracebase/DataRepo/utils/exceptions.py", line 2295, in get_buffered_traceback_string
    for step in traceback.format_stack()
EXCEPTION3(ERROR): ProgrammingError: Cannot delete a file [/tracebasedev-archive/archive/archive_files/2024-08/ms_data/exp027f4_free_M01_01_plasma.mzXML] from the os that is associated with existing ArchiveFile database record: {'id': 654, 'filename': 'exp027f4_free_M01_01_plasma.mzXML', 'checksum': 'f9d2074dff00cf659a0888617bc92163725a45e4', 'file_location': <FieldFile: archive_files/2024-08/ms_data/exp027f4_free_M01_01_plasma.mzXML>, 'data_type': 2, 'data_format': 4}.
mzXML file rollback disk archive clean up stats: 0 deleted, 0 failed to be deleted, and 0 expected files did not exist.
  File "/var/www/tracebase/manage.py", line 22, in <module>
    main()
  File "/var/www/tracebase/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/var/www/tracebase/DataRepo/management/commands/load_table.py", line 408, in handle_wrapper
    retval = fn(self, *args, **options)
  File "/var/www/tracebase/DataRepo/management/commands/load_msruns.py", line 150, in handle
    self.load_data()
  File "/var/www/tracebase/DataRepo/management/commands/load_table.py", line 448, in load_data
    return self.loader.load_data(*args, **kwargs)
  File "/var/www/tracebase/DataRepo/loaders/base/table_loader.py", line 2187, in load_wrapper
    self.aggregated_errors_object.buffer_exception(
  File "/var/www/tracebase/DataRepo/utils/exceptions.py", line 2315, in buffer_exception
    buffered_tb_str = self.get_buffered_traceback_string()
  File "/var/www/tracebase/DataRepo/utils/exceptions.py", line 2295, in get_buffered_traceback_string
    for step in traceback.format_stack()
EXCEPTION2(ERROR): MissingRecords: The following records were missing either because they were not in the corresponding sheets or because errors were encountered during their load attempt that prevented their creation (in which case you will see those errors, likely above this one):
1 Sample records were not found (using search field(s): name) with values found in the Peak Annotation Details sheet/file:
	exp027f4_free_M01_01_plasma from row(s): ['no row number supplied']
```

And here is the final summary exception:

```
AggregatedErrors Summary (2 errors / 0 warnings):
	EXCEPTION1(ERROR): ProgrammingError: Cannot delete a file [/tracebasedev-archive/archive/archive_files/2024-08/ms_data/exp027f4_free_M01_01_plasma.mzXML] from the os that is associated with existing ArchiveFile database record: {'id': 654, 'filename': 'exp027f4_free_M01_01_plasma.mzXML', 'checksum': 'f9d2074dff00cf659a0888617bc92163725a45e4', 'file_location': <FieldFile: archive_files/2024-08/ms_data/exp027f4_free_M01_01_plasma.mzXML>, 'data_type': 2, 'data_format': 4}.
	EXCEPTION2(ERROR): MissingRecords: The following records were missing either because they were not in the corresponding sheets or because errors were encountered during their load attempt that prevented their creation (in which case you will see those errors, likely above this one):
1 Sample records were not found (using search field(s): name) with values found in the Peak Annotation Details sheet/file:
	exp027f4_free_M01_01_plasma from row(s): ['no row number supplied']

Traceback (most recent call last):
  File "/var/www/tracebase/manage.py", line 22, in <module>
    main()
  File "/var/www/tracebase/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/tracebase/lib/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/tracebase/lib/python3.9/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/tracebase/lib/python3.9/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/tracebase/lib/python3.9/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/var/www/tracebase/DataRepo/management/commands/load_table.py", line 425, in handle_wrapper
    raise self.saved_aes
  File "/var/www/tracebase/DataRepo/management/commands/load_table.py", line 408, in handle_wrapper
    retval = fn(self, *args, **options)
  File "/var/www/tracebase/DataRepo/management/commands/load_msruns.py", line 150, in handle
    self.load_data()
  File "/var/www/tracebase/DataRepo/management/commands/load_table.py", line 448, in load_data
    return self.loader.load_data(*args, **kwargs)
  File "/var/www/tracebase/DataRepo/loaders/base/table_loader.py", line 2271, in load_wrapper
    raise self.aggregated_errors_object
DataRepo.utils.exceptions.AggregatedErrors: 2 exceptions occurred, including type(s): [ProgrammingError, MissingRecords].
AggregatedErrors Summary (2 errors / 0 warnings):
	EXCEPTION1(ERROR): ProgrammingError: Cannot delete a file [/tracebasedev-archive/archive/archive_files/2024-08/ms_data/exp027f4_free_M01_01_plasma.mzXML] from the os that is associated with existing ArchiveFile database record: {'id': 654, 'filename': 'exp027f4_free_M01_01_plasma.mzXML', 'checksum': 'f9d2074dff00cf659a0888617bc92163725a45e4', 'file_location': <FieldFile: archive_files/2024-08/ms_data/exp027f4_free_M01_01_plasma.mzXML>, 'data_type': 2, 'data_format': 4}.
	EXCEPTION2(ERROR): MissingRecords: The following records were missing either because they were not in the corresponding sheets or because errors were encountered during their load attempt that prevented their creation (in which case you will see those errors, likely above this one):
1 Sample records were not found (using search field(s): name) with values found in the Peak Annotation Details sheet/file:
	exp027f4_free_M01_01_plasma from row(s): ['no row number supplied']

Scroll up to see tracebacks for these exceptions printed as they were encountered.
```

**Comment by hepcat72** [comment]
Also note that the following are the stats from the load attempt:

```
Done.
MSRunSample records created: [0], existed: [0], updated: [0], skipped [1], errored: [0], and warned: [0].
PeakGroup records created: [0], existed: [0], updated: [0], skipped [0], errored: [0], and warned: [0].
ArchiveFile records created: [2], existed: [0], updated: [0], skipped [0], errored: [0], and warned: [0].
```

So it looks like there was no MSRunSample record created.  That means that the attempt to create it never happened.  It was during the attempt to find an existing record when it was discovered that the `Sample` record didn't exist, which meant that the `MSRunSample` record couldn't exist (and couldn't be created).  That's what should be a warning.

**Comment by hepcat72** [comment]
...and the 2 `ArchiveFile` records are the mzXML and the associated RAW file.

**Comment by hepcat72** [comment]
So it appears that the problem is that `for rec in self.created_mzxml_archive_file_recs:` is looping on the archive file records it created, but is complaining that it can't delete them because the records exist, which is circular logic.  What was intended here was to prevent the deletion of pre-existing `ArchiveFile` records.  Note the comment above the conditional that is checking the record from the loop:
```
# To be extra safe, we will confirm that the record does not exist in the database before deleting
if exists_in_db(rec):
```
